### ISSUE TITLE
Todo(?)

### ISSUE THREAD

**Issue by arkhlima** [arkhlima/kanakata#1]
Here are some features and gimmicks that I ((probably)) will work on:

- [x] Submit & reset button for mobile users -> https://github.com/arkhlima/kanakata/commit/ddf481c2a975a747ca1dbd6282664dbb48e60273 https://github.com/arkhlima/kanakata/commit/9a564c36b9d78481c2794ebbbd00dfc0c192a606 https://github.com/arkhlima/kanakata/commit/5a2c503d5268b21a35f8d7257c365f3fdf63e4b0
- [ ] #3
- [ ] Print version.
- [ ] Quiz stats/details & play again button in the results dialog.
- [x] Look-alike katakana chars — refer to https://kana.pro/ -> https://github.com/arkhlima/kanakata/commit/1480988edbcd7ac8e24a3e2896a66033e58de938 https://github.com/arkhlima/kanakata/commit/fa81560e132061fae47a8c47d478a9974eca43ad
- [x] Look-alike hiragana chars(?) https://github.com/arkhlima/kanakata/commit/aefed90a9e65b0f98ccd40c597d1be4c565b830d
- [ ] Sound effect when the answer is right/wrong.
- [ ] Quiz options — e.g. total questions, kana to romaji, time mode, etc.
- [ ] Unit/integration testing — boo.
- [ ] Meta tags
- [ ] PWA implementation(?)
